#!/bin/busybox bash

/bin/busybox --install -s bin

busybox mount -t proc proc /proc
busybox mount -t sysfs sysfs /sys

echo "welcome to kernel 2.26.6"
cd home

# ip addr add 10.0.2.15/24 dev eth0
# ip link set eth0 up
# ip route add default via 10.0.2.2
# ip addr add 10.0.2.36/24 dev eth0
# ip link set eth0 up
# ip route add default via 10.0.0.2 dev eth0

ip link set eth0 up
ip addr add 10.0.0.2/24 dev eth0
ip route add default via 10.0.0.1 dev eth0

insmod hook.ko

exec /bin/busybox bash
